language: elixir
elixir:
  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
  - 1.0.4
  - 1.0.5
  - 1.1.0
sudo: false
notifications:
  recipients:
    - self@falood.me
before_script:
  - mix deps.get --only test
